//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfSew
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SewEntities1 : DbContext
    {
        public SewEntities1()
            : base("name=SewEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Заказ> Заказ { get; set; }
        public DbSet<Заказанные_изделия> Заказанные_изделия { get; set; }
        public DbSet<Изделия> Изделия { get; set; }
        public DbSet<Пользователь> Пользователь { get; set; }
        public DbSet<Склад_ткани> Склад_ткани { get; set; }
        public DbSet<Склад_фурнитуры> Склад_фурнитуры { get; set; }
        public DbSet<Ткани> Ткани { get; set; }
        public DbSet<Ткани_изделия> Ткани_изделия { get; set; }
        public DbSet<Фурнитура> Фурнитура { get; set; }
        public DbSet<Фурнитура_изделия> Фурнитура_изделия { get; set; }
    }
}
