//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfSew
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProducts
    {
        public int article { get; set; }
        public string name { get; set; }
        public string width { get; set; }
        public string length { get; set; }
        public byte[] image { get; set; }
        public string comment { get; set; }
    }
}
