//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfSew
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTextile
    {
        public int textileArticle { get; set; }
        public string name { get; set; }
        public string color { get; set; }
        public string picture { get; set; }
        public byte[] image { get; set; }
        public string composition { get; set; }
        public string width { get; set; }
        public string length { get; set; }
        public Nullable<decimal> cost { get; set; }
    }
}
