//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfSew
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        public Заказ()
        {
            this.Заказанные_изделия = new HashSet<Заказанные_изделия>();
        }
    
        public string Номер { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public string Этап_выполнения { get; set; }
        public string Заказчик { get; set; }
        public string Менеджер { get; set; }
        public Nullable<decimal> Стоимость { get; set; }
    
        public virtual Пользователь Пользователь { get; set; }
        public virtual Пользователь Пользователь1 { get; set; }
        public virtual ICollection<Заказанные_изделия> Заказанные_изделия { get; set; }
    }
}
