//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfSew
{
    using System;
    using System.Collections.Generic;
    
    public partial class Изделия
    {
        public Изделия()
        {
            this.Заказанные_изделия = new HashSet<Заказанные_изделия>();
            this.Ткани_изделия = new HashSet<Ткани_изделия>();
            this.Фурнитура_изделия = new HashSet<Фурнитура_изделия>();
        }
    
        public string Артикул { get; set; }
        public string Наименование { get; set; }
        public Nullable<double> Ширина { get; set; }
        public Nullable<double> Длина { get; set; }
        public byte[] Изображение { get; set; }
        public string Комментарий { get; set; }
    
        public virtual ICollection<Заказанные_изделия> Заказанные_изделия { get; set; }
        public virtual ICollection<Ткани_изделия> Ткани_изделия { get; set; }
        public virtual ICollection<Фурнитура_изделия> Фурнитура_изделия { get; set; }
    }
}
