//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfSew
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователь
    {
        public Пользователь()
        {
            this.Заказ = new HashSet<Заказ>();
            this.Заказ1 = new HashSet<Заказ>();
        }
    
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public string Роль { get; set; }
        public string Наименование { get; set; }
    
        public virtual ICollection<Заказ> Заказ { get; set; }
        public virtual ICollection<Заказ> Заказ1 { get; set; }
    }
}
