//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfSew
{
    using System;
    using System.Collections.Generic;
    
    public partial class Фурнитура_изделия
    {
        public int Артикул_фурнитуры_изделия { get; set; }
        public string Артикул_фурнитуры { get; set; }
        public string Артикул_изделия { get; set; }
        public string Размещение { get; set; }
        public Nullable<double> Ширина { get; set; }
        public Nullable<double> Длина { get; set; }
        public string Поворот { get; set; }
        public int Количество { get; set; }
    
        public virtual Изделия Изделия { get; set; }
        public virtual Фурнитура Фурнитура { get; set; }
    }
}
