//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfSew
{
    using System;
    using System.Collections.Generic;
    
    public partial class Фурнитура
    {
        public Фурнитура()
        {
            this.Склад_фурнитуры = new HashSet<Склад_фурнитуры>();
            this.Фурнитура_изделия = new HashSet<Фурнитура_изделия>();
        }
    
        public string Артикул { get; set; }
        public string Наименование { get; set; }
        public string Тип { get; set; }
        public Nullable<double> Ширина { get; set; }
        public Nullable<double> Длина { get; set; }
        public Nullable<double> Вес { get; set; }
        public byte[] Изображение { get; set; }
        public Nullable<decimal> Цена { get; set; }
    
        public virtual ICollection<Склад_фурнитуры> Склад_фурнитуры { get; set; }
        public virtual ICollection<Фурнитура_изделия> Фурнитура_изделия { get; set; }
    }
}
